// bot.js — Basit Telegram Botu (kurulum gerekmez!)
const TOKEN = '8996849772:AAGT8m9pcPybVgdLtcacYr09JzYX30GxgkQ';
const API = `https://api.telegram.org/bot${TOKEN}`;
const fs = require('fs');
const { execSync } = require('child_process');
const path = require('path');

const DATA_FILE = path.join(__dirname, 'data', 'sorular.json');
const userStates = {};
const DERSLER = ['Tarih', 'Coğrafya', 'Vatandaşlık', 'Türkçe', 'Matematik', 'Güncel'];
const SEVIYELER = ['Ortaöğretim', 'Önlisans', 'Lisans'];
const LETTERS = 'ABCDE';

function loadQuestions() {
  try {
      if (!fs.existsSync(DATA_FILE)) return { sorular: [] };
          return JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
            } catch (e) { return { sorular: [] }; }
            }

            function saveQuestions(data) {
              const dir = path.dirname(DATA_FILE);
                if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
                  fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2));
                  }

                  async function tg(method, body) {
                    try {
                        const res = await fetch(`${API}/${method}`, {
                              method: 'POST',
                                    headers: { 'Content-Type': 'application/json' },
                                          body: JSON.stringify(body)
                                              });
                                                  return await res.json();
                                                    } catch (e) { console.error('API hata:', e.message); return null; }
                                                    }

                                                    async function send(chatId, text, extra = {}) {
                                                      return tg('sendMessage', { chat_id: chatId, text, parse_mode: 'Markdown', ...extra });
                                                      }

                                                      async function getFileUrl(fileId) {
                                                        const d = await tg('getFile', { file_id: fileId });
                                                          if (!d || !d.ok) return null;
                                                            return `https://api.telegram.org/file/bot${TOKEN}/${d.result.file_path}`;
                                                            }

                                                            function mainMenu() {
                                                              return { reply_markup: { inline_keyboard: [
                                                                  [{ text: '➕ Yeni Soru Ekle', callback_data: 'new_question' }],
                                                                      [{ text: '📊 İstatistik', callback_data: 'stats' }, { text: '❓ Yardım', callback_data: 'help' }]
                                                                        ] } };
                                                                        }

                                                                        function startFlow(chatId) {
                                                                          userStates[chatId] = { step: 'ders' };
                                                                            send(chatId, '📚 *Yeni Soru Ekleme*\n\nHangi ders?', {
                                                                                reply_markup: { inline_keyboard: DERSLER.map(d => [{ text: d, callback_data: 'ders_' + d }]) }
                                                                                  });
                                                                                  }

                                                                                  async function finish(chatId) {
                                                                                    const s = userStates[chatId];
                                                                                      if (!s) return;
                                                                                        const data = loadQuestions();
                                                                                          const q = {
                                                                                              id: 'tg_' + Date.now() + '_' + Math.random().toString(36).slice(2, 8),
                                                                                                  ders: s.ders, kategori: s.kategori, seviye: s.seviye,
                                                                                                      soru: s.soru, secenekler: s.secenekler, dogru: s.dogru,
                                                                                                          aciklama: s.aciklama || '', gorsel: s.gorsel || null,
                                                                                                              eklenme: Date.now(), kaynak: 'telegram'
                                                                                                                };
                                                                                                                  data.sorular.unshift(q);
                                                                                                                    saveQuestions(data);
                                                                                                                      delete userStates[chatId];
                                                                                                                        send(chatId,
                                                                                                                            `🎉 *Soru kaydedildi!*\n\n📚 ${q.ders}\n📂 ${q.kategori}\n🎓 ${q.seviye}\n✔️ Doğru: ${LETTERS[q.dogru]}\n🖼 Görsel: ${q.gorsel ? '✅' : '—'}\n\n📊 Toplam *${data.sorular.length}* soru`,
                                                                                                                                mainMenu());
                                                                                                                                }

                                                                                                                                async function sendHelp(chatId) {
                                                                                                                                  send(chatId,
                                                                                                                                      `📖 *Komutlar*\n\n*/soru* — Soru ekle\n*/gorsel* — Görsel ekle\n*/iptal* — İptal\n*/istatistik* — Kaç soru var\n*/yardim* — Bu menü`);
                                                                                                                                      }

                                                                                                                                      async function sendStats(chatId) {
                                                                                                                                        const data = loadQuestions();
                                                                                                                                          const byD = {};
                                                                                                                                            data.sorular.forEach(q => { byD[q.ders] = (byD[q.ders] || 0) + 1; });
                                                                                                                                              let t = `📊 *Toplam ${data.sorular.length} soru*\n\n`;
                                                                                                                                                Object.keys(byD).forEach(d => { t += `• ${d}: ${byD[d]}\n`; });
                                                                                                                                                  send(chatId, t);
                                                                                                                                                  }

                                                                                                                                                  async function handleUpdate(update) {
                                                                                                                                                    // Callback (buton)
                                                                                                                                                      if (update.callback_query) {
                                                                                                                                                          const q = update.callback_query;
                                                                                                                                                              const chatId = q.message.chat.id;
                                                                                                                                                                  const data = q.data;
                                                                                                                                                                      await tg('answerCallbackQuery', { callback_query_id: q.id });

                                                                                                                                                                          if (data === 'new_question') return startFlow(chatId);
                                                                                                                                                                              if (data === 'help') return sendHelp(chatId);
                                                                                                                                                                                  if (data === 'stats') return sendStats(chatId);

                                                                                                                                                                                      if (data.startsWith('ders_')) {
                                                                                                                                                                                            userStates[chatId].ders = data.replace('ders_', '');
                                                                                                                                                                                                  userStates[chatId].step = 'kategori';
                                                                                                                                                                                                        return send(chatId, `✅ Ders: *${userStates[chatId].ders}*\n\n📂 Kategori yaz:`);
                                                                                                                                                                                                            }
                                                                                                                                                                                                                if (data.startsWith('seviye_')) {
                                                                                                                                                                                                                      userStates[chatId].seviye = data.replace('seviye_', '');
                                                                                                                                                                                                                            userStates[chatId].step = 'soru';
                                                                                                                                                                                                                                  return send(chatId, `✅ Seviye: *${userStates[chatId].seviye}*\n\n📝 Soru metnini yaz:`);
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                          if (data.startsWith('dogru_')) {
                                                                                                                                                                                                                                                userStates[chatId].dogru = LETTERS.indexOf(data.replace('dogru_', ''));
                                                                                                                                                                                                                                                      userStates[chatId].step = 'aciklama';
                                                                                                                                                                                                                                                            return send(chatId, `✅ Doğru: *${data.replace('dogru_', '')}*\n\n💬 Açıklama yaz (_yok_ = atla):`);
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    if (data === 'gorsel_evet') {
                                                                                                                                                                                                                                                                          userStates[chatId].step = 'gorsel_bekle';
                                                                                                                                                                                                                                                                                return send(chatId, `📸 *Görsel Bekleniyor*\n\nŞimdi fotoğrafı gönder.`);
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                        if (data === 'gorsel_hayir') return finish(chatId);
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                            // Metin
                                                                                                                                                                                                                                                                                              if (update.message && update.message.text) {
                                                                                                                                                                                                                                                                                                  const msg = update.message;
                                                                                                                                                                                                                                                                                                      const chatId = msg.chat.id;
                                                                                                                                                                                                                                                                                                          const text = msg.text;
                                                                                                                                                                                                                                                                                                              const state = userStates[chatId];

                                                                                                                                                                                                                                                                                                                  if (text.startsWith('/start')) {
                                                                                                                                                                                                                                                                                                                        userStates[chatId] = { step: 'idle' };
                                                                                                                                                                                                                                                                                                                              return send(chatId, `👋 *KPSS BilgiMatik Botu*\n\n/soru ile soru ekle!`, mainMenu());
                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                      if (text.startsWith('/soru')) return startFlow(chatId);
                                                                                                                                                                                                                                                                                                                                          if (text.startsWith('/yardim')) return sendHelp(chatId);
                                                                                                                                                                                                                                                                                                                                              if (text.startsWith('/istatistik')) return sendStats(chatId);
                                                                                                                                                                                                                                                                                                                                                  if (text.startsWith('/iptal')) {
                                                                                                                                                                                                                                                                                                                                                        delete userStates[chatId];
                                                                                                                                                                                                                                                                                                                                                              return send(chatId, '❌ İptal edildi.', mainMenu());
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                      if (text.startsWith('/gorsel')) {
                                                                                                                                                                                                                                                                                                                                                                            if (!state || state.step === 'idle') return send(chatId, '⚠️ Önce /soru yaz.');
                                                                                                                                                                                                                                                                                                                                                                                  state.prevStep = state.step;
                                                                                                                                                                                                                                                                                                                                                                                        state.step = 'gorsel_bekle';
                                                                                                                                                                                                                                                                                                                                                                                              return send(chatId, `📸 Görsel modu açıldı. Kaldığın adım: *${state.prevStep}*\n\nFotoğrafı gönder.`);
                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                      if (!state) return;

                                                                                                                                                                                                                                                                                                                                                                                                          switch (state.step) {
                                                                                                                                                                                                                                                                                                                                                                                                                case 'kategori':
                                                                                                                                                                                                                                                                                                                                                                                                                        state.kategori = text;
                                                                                                                                                                                                                                                                                                                                                                                                                                state.step = 'seviye';
                                                                                                                                                                                                                                                                                                                                                                                                                                        return send(chatId, `✅ Kategori: *${text}*\n\n🎓 Seviye seç:`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  reply_markup: { inline_keyboard: SEVIYELER.map(s => [{ text: s, callback_data: 'seviye_' + s }]) }
                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 'soru':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        state.soru = text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                state.step = 'secenek';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        state.secenekler = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                state.secenekIdx = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return send(chatId, `✅ Soru kaydedildi.\n\n🔤 *A* seçeneğini yaz (_/gorsel_ = görsel ekle):`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              case 'secenek':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      state.secenekler.push(text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              state.secenekIdx++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (state.secenekIdx < 5) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const L = LETTERS[state.secenekIdx];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return send(chatId, `✅ *${LETTERS[state.secenekIdx - 1]}* kaydedildi.\n\n🔤 *${L}* yaz:`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            state.step = 'dogru';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return send(chatId, `✅ Tüm şıklar alındı.\n\n✔️ *Doğru cevap?*`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  reply_markup: { inline_keyboard: [[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { text: 'A', callback_data: 'dogru_A' }, { text: 'B', callback_data: 'dogru_B' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { text: 'C', callback_data: 'dogru_C' }, { text: 'D', callback_data: 'dogru_D' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { text: 'E', callback_data: 'dogru_E' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]] }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 'aciklama':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        state.aciklama = text.toLowerCase() === 'yok' ? '' : text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return send(chatId, `📸 *Bu soruya görsel eklemek ister misin?*`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          reply_markup: { inline_keyboard: [[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { text: '📷 Evet', callback_data: 'gorsel_evet' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { text: '⏭ Hayır, kaydet', callback_data: 'gorsel_hayir' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]] }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          case 'gorsel_bekle':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return send(chatId, `⚠️ Lütfen *fotoğraf* gönder (metin değil).`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Fotoğraf
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (update.message && update.message.photo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const chatId = update.message.chat.id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const state = userStates[chatId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!state || state.step !== 'gorsel_bekle') return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const photo = update.message.photo[update.message.photo.length - 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const url = await getFileUrl(photo.file_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    state.gorsel = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const back = state.prevStep || 'aciklama';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            state.prevStep = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (back === 'aciklama') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      send(chatId, '✅ Görsel kaydedildi.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return finish(chatId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    state.step = back;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        send(chatId, '✅ Görsel kaydedildi. Kaldığın yerden devam et.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Long polling
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          let offset = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          async function poll() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('🤖 Bot çalışıyor... Telegram\'dan /soru yaz');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              while (true) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const res = await tg('getUpdates', { offset, timeout: 30 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (res && res.ok && res.result.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (const u of res.result) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                offset = u.update_id + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          handleUpdate(u).catch(e => console.error('Hata:', e.message));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error('Poll hata:', e.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await new Promise(r => setTimeout(r, 3000));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!TOKEN || TOKEN === 'BURAYA_TOKEN_YAZ') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log('❌ Önce bot.js içindeki TOKEN kısmına bot tokenini yaz!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  poll();
